# Generated by Django 6.0.7 on 2026-08-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_procedure', models.CharField(choices=[('appel_civil', 'Appel civil'), ('contestation', 'Contestation'), ('requete_introductive', 'Requête introductive')], max_length=50)),
                ('date_debut', models.DateField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('ferme', 'Fermé'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='clients.client')),
            ],
        ),
    ]
