# Generated by Django 6.0.7 on 2026-08-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0003_profilavocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilavocat',
            name='seuil_orange',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='profilavocat',
            name='seuil_rouge',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
