# Generated by Django 6.0.7 on 2026-08-05 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_profilavocat_seuil_orange_profilavocat_seuil_rouge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Taux horaire du dossier ($)'),
        ),
        migrations.AddField(
            model_name='profilavocat',
            name='taux_horaire_defaut',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Taux horaire par défaut ($)'),
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_communication', models.CharField(choices=[('courriel', 'Courriel'), ('appel', 'Appel téléphonique'), ('lettre', 'Lettre'), ('autre', 'Autre')], default='courriel', max_length=20, verbose_name='Type')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('avocat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL, verbose_name='Avocat')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='dossiers.dossier')),
            ],
        ),
    ]
