# Generated by Django 6.0.7 on 2026-08-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_avocat'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='client',
            name='nom_representant',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du représentant'),
        ),
        migrations.AddField(
            model_name='client',
            name='numero_entreprise',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name="Numéro d'entreprise (NEQ)"),
        ),
        migrations.AddField(
            model_name='client',
            name='raison_sociale',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Raison sociale'),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('individu', 'Individu'), ('compagnie', 'Compagnie')], default='individu', max_length=20, verbose_name='Type de client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Courriel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
