# Generated by Django 6.0.7 on 2026-08-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_delai', models.CharField(max_length=100)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('respecte', 'Respecté'), ('depasse', 'Dépassé')], default='a_venir', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='dossiers.dossier')),
            ],
        ),
    ]
