# Generated by Django 6.0.7 on 2026-08-04 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_dossier_avocat'),
        ('echeances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField()),
                ('mode', models.CharField(choices=[('presentiel', 'Présentiel'), ('visio', 'Visioconférence'), ('telephone', 'Téléphone')], default='presentiel', max_length=20)),
                ('lieu_ou_lien', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('complete', 'Complété'), ('annule', 'Annulé')], default='planifie', max_length=20)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='dossiers.dossier')),
            ],
        ),
    ]
