# Generated by Django 6.0.7 on 2026-08-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0003_rendezvous_avocat_rendezvous_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='alerte_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='echeance',
            name='date_alerte_envoyee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
