# Generated by Django 6.0.7 on 2026-08-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echeances', '0004_echeance_alerte_envoyee_echeance_date_alerte_envoyee'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
