# Generated by Django 6.0.7 on 2026-08-04 23:27

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0004_profilavocat_seuil_orange_profilavocat_seuil_rouge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=documents.models.chemin_upload, verbose_name='Fichier')),
                ('nom_original', models.CharField(max_length=255, verbose_name='Nom original')),
                ('taille', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name="Date d'upload")),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dossiers.dossier')),
            ],
        ),
    ]
