# Generated by Django 6.0.7 on 2026-08-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='taille',
        ),
        migrations.AddField(
            model_name='document',
            name='taille_octets',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='document',
            name='type_fichier',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Type de fichier'),
        ),
    ]
