# Generated by Django 6.0.7 on 2026-08-04 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0002_remove_document_taille_document_taille_octets_and_more'),
        ('dossiers', '0004_profilavocat_seuil_orange_profilavocat_seuil_rouge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploades', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='document',
            name='categorie',
            field=models.CharField(choices=[('avis_juridique', 'Avis juridique'), ('contrat', 'Contrat'), ('correspondance', 'Correspondance'), ('preuve', 'Preuve'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='document',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.client'),
        ),
        migrations.AddField(
            model_name='document',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='dossiers.dossier'),
        ),
    ]
