# Generated by Django 6.0.7 on 2026-08-05 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_auteur_document_categorie_document_client_and_more'),
        ('dossiers', '0004_profilavocat_seuil_orange_profilavocat_seuil_rouge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('mise_en_demure', 'Mise en demeure')], default='mise_en_demure', max_length=50, verbose_name='Type de document')),
                ('contenu_brouillon', models.TextField(verbose_name='Contenu du brouillon')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('envoye', 'Envoyé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_generes', to='dossiers.dossier')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
        ),
    ]
