# Generated by Django 6.0.7 on 2026-08-05 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentgenere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgenere',
            name='parametres_generation',
            field=models.TextField(blank=True, default='', verbose_name='Paramètres de génération'),
        ),
        migrations.CreateModel(
            name='JournalDocumentGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generation', 'Génération'), ('modification', 'Modification'), ('validation', 'Validation'), ('rejet', 'Rejet')], max_length=20, verbose_name='Action')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('details', models.TextField(blank=True, default='', verbose_name='Détails')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='documents.documentgenere')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
