# Generated by Django 6.0.7 on 2026-08-05 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentgenere_parametres_generation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_analyse', models.TextField(verbose_name='Analyse')),
                ('date_analyse', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'analyse")),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_documents', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='documents.document')),
            ],
        ),
    ]
