# Generated by Django 6.0.7 on 2026-08-05 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plan', models.CharField(default='Standard', max_length=50, verbose_name='Plan')),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix mensuel ($)')),
                ('quota_mensuel', models.PositiveIntegerField(default=50, verbose_name='Quota mensuel (appels IA)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('avocat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_usage', models.CharField(choices=[('generation', 'Génération'), ('analyse', 'Analyse')], max_length=20, verbose_name='Type')),
                ('octets', models.PositiveIntegerField(default=0, verbose_name='Taille (octets)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=7, verbose_name='Mois (AAAA-MM)')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Montant ($)')),
                ('payee', models.BooleanField(default=False, verbose_name='Payée')),
                ('date_emission', models.DateTimeField(auto_now_add=True, verbose_name="Date d'émission")),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('avocat', 'mois')},
            },
        ),
    ]
