# Generated by Django 6.0.7 on 2026-08-05 03:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_profilavocat_seuil_orange_profilavocat_seuil_rouge'),
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempsTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Début')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_travail', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temps_travail', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Temps de travail',
                'verbose_name_plural': 'Temps de travail',
                'ordering': ['-debut'],
            },
        ),
    ]
