# Generated by Django 6.0.7 on 2026-08-05 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_dossier_taux_horaire_and_more'),
        ('facturation', '0002_tempstravail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('duree_minutes', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('categorie_activite', models.CharField(choices=[('redaction', 'Rédaction'), ('recherche', 'Recherche'), ('rencontre', 'Rencontre client'), ('procedure', 'Procédure'), ('autre', 'Autre')], default='redaction', max_length=20, verbose_name="Catégorie d'activité")),
                ('taux_horaire_applique', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Taux horaire appliqué ($)')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Montant ($)')),
                ('non_facturable', models.BooleanField(default=False, verbose_name='Non facturable')),
                ('saisie_manuelle', models.BooleanField(default=False, verbose_name='Saisie manuelle')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('avocat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_temps', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_temps', to='dossiers.dossier')),
            ],
            options={
                'verbose_name': 'Entrée de temps',
                'verbose_name_plural': 'Entrées de temps',
                'ordering': ['-date', '-cree_le'],
            },
        ),
    ]
