# Generated by Django 6.0.7 on 2026-08-15 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_adresse_client_nom_representant_and_more'),
        ('dossiers', '0005_dossier_taux_horaire_and_more'),
        ('facturation', '0003_entreetemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='dossiers.dossier'),
        ),
    ]
