# Generated by Django 6.0.7 on 2026-08-15 02:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_adresse_client_nom_representant_and_more'),
        ('facturation', '0004_facture_client_facture_dossier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('avocat', 'client', 'mois')},
        ),
    ]
