# Generated by Django 6.0.7 on 2026-08-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_alter_facture_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée')], default='brouillon', max_length=20, verbose_name='Statut'),
        ),
    ]
